version: '3.4'
services:
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: fikret
      WORDPRESS_DB_PASSWORD: 12345
      WORDPRESS_DB_NAME: blogdb
    volumes:
      - wordpress:/var/www/html
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: blogdb
      MYSQL_USER: fikret
      MYSQL_PASSWORD: 12345
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - db:/var/lib/mysql
volumes:
  wordpress:
  db: