version: '3.4'
services:
  todo-app:
    build: .
    container_name: todo-app
    ports:
      - 3001:3000
  mongodb:
    image: mongo
    ports:
      - 4000:27017
    volumes:
      - todo-app-data:/data/db
volumes:
  todo-app-data:
      